### PR TITLE
Support monochrome bulbs and remove warning about set_rgbw()

### PR DESCRIPTION
**Pull request by mjg59**
Add support for identifying monochrome bulbs, and remove the warning about
set_rgbw() - it seems to work fine on these bulbs.

### CODE REVIEW

**Comment by mjg59** [comment]
I wrote a module myself and then realised you'd already done one - this brings over another couple of bits I worked out, including support for the monochrome Mipow bulbs.

**Comment by amahlaka** [comment]
There is set_rgbw that is used to control both color and white, I have intentionally separated set_rgb from set_rgbw for functional reasons,

**Comment by mjg59** [comment]
set_rgb() is still there, purely as a wrapper for set_rgbw(). What functional issues are you seeing with set_rgbw()? On this hardware I can't see any behavioural difference.

**Comment by amahlaka** [comment]
It's a particular another solution I have implemented on a home automation
system, so changing it breaks a lot :p

**Comment by mjg59** [comment]
I don't understand - the set_rgb() call is still there and should behave in exactly the same way. Can you describe what the problem would be?

**Comment by amahlaka** [comment]
Also, why remove the set_effect?

**Comment by mjg59** [comment]
It wasn't documented, so I missed it - I'll add it back.

**Comment by mjg59** [comment]
The order of characteristics on your bulb is different to mine, so your effects code doesn't work right now. What's the UUID of the handle you perform the effects write to on your bulb?

**Comment by mjg59** [comment]
Ah, never mind, it's fffb. Your bulb definitely has a different layout to mine, so it's necessary to use the UUID rather than the handle number to be compatible across the range. This should work for both.

**Comment by amahlaka** [comment]
sorry for not giving any update on this, i will test this and see if it works

**Comment by amahlaka** [comment]
Hi again @mjg59  i noticed that you also had made a home assistant component for mipow,
what model is the light that you have? any pics

**Comment by amahlaka** [comment]
also, i was using this to find most of the handles: https://github.com/Phhere/Playbulb

**Comment by amahlaka** [comment]
If you want you can finish up the Home assistant component for this light, i just hope for the effects to be there, at least flashing :+1:

**Comment by amahlaka** [comment]
does this version also support rgb values for colors?

**Pull request merged**
